### ISSUE TITLE
Why are certain parameters declared with the final modifier?

### ISSUE THREAD

**Issue by manuelkollus** [zalando/nakadi#1081]
Hello,
as I have seen from the source code, some parameters are declared with the final modifier. I am of the opinion that this is unnecessary.

Here are some reasons:
- It makes the source code confusing.
- No performance advantages, maybe some JIT compilers are prefers it, but by default it doesn't bring anything.

I hope that the @zalando team is of the same opinion and will avoid this in the future.

Yours sincerely,
Manuel Kollus

**Comment by rcillo** [comment]
Hi @manuelkollus the usage of final is mandatory throughout the codebase and not only for `some` parameters. All parameters are `final`. The reason for that is to promote the development of immutable code, where parameters are not reassigned a different value. Our team considers immutable values to make it easier to reason about code and thus producing bugs less often.

The reason is not performance but clarity. It's similar to a scala `val` instead of `var` and with help from checkstyle it's easier to enforce this.
