### ISSUE TITLE
EntityType.owning_application is required?

### ISSUE THREAD

**Issue by bocytko** [zalando/nakadi#145]
Creation of events without `owning_application` fails with an error:

```
{
  "type": "http://httpstatus.es/422",
  "title": "Unprocessable Entity",
  "detail": "Field \"owning_application\" may not be null\n",
  "status": 422
}
```

Is `owning_application` a required field for `EventType` now? The API spec states otherwise.

```
{
 "name": "test",
 "category": "data",
 "schema": {
  "type": "json_schema",
  "schema": "{ \"properties\": { \"order_number\": { \"type\": \"string\" } } }"
 }
}
```

**Comment by AlexanderYastrebov** [comment]
Also tried to create only with required name and category:
```
{"status":422,"title":"Unprocessable Entity","detail":"Field \"schema\" may not be null\nField \"owning_application\" may not be null\n","type":"http://httpstatus.es/422"}
```

**Comment by v-stepanov** [comment]
It should be a required field.
We updated the API
https://github.com/zalando/nakadi/blob/nakadi-jvm/api/nakadi-event-bus-api.yaml#L1196

**Comment by AlexanderYastrebov** [comment]
Looks like schema is also required

**Comment by valgog** [comment]
If schema is required, it looks like a bug

**Comment by rcillo** [comment]
I'll fix it. This was my first task in the project and I misunderstood this https://github.com/zalando/nakadi/blob/nakadi-jvm/api/nakadi-event-bus-api.yaml#L1198-L1211 as requiring the schema.

But in fact, if present, it should have "schema.schema" field. This is quite confusing since the parent field and the child field have the same name.

You should expect a commit fixing it today.
