### ISSUE TITLE
Nakadi throws 500 when an event is published which does not conform to a json schema

### ISSUE THREAD

**Issue by bpraveen** [zalando/nakadi#167]
java.lang.RuntimeException: Could not read url: /event-types/PRODUCT_AVAILABILITY_UPDATES/events, status code: 500, message: Internal Server Error, result: {"type":"http://httpstatus.es/500","title":"Internal Server Error","status":500,"detail":"An internal error happened. Please report it. (ETIF4fVmOryh8ZOUiC7hkrbx2it)"}

**Comment by rcillo** [comment]
The referred event-type has been created previously to the schema validation feature. This feature introduces some backward incompatibilities, such that every event type whose schema is not a valid json should stop working.

In this case, the event type:

```json
{
    "name": "PRODUCT_AVAILABILITY_UPDATES",
    "owning_application": "product-availability",
    "category": "data",
    "partitioning_key_fields": [],
    "schema": {
      "type": "json_schema",
      "schema": "SCHEMA"
    }
  }
```

Contains a schema "SCHEMA" which is not valid json. That's why you get a 500. We'll delete this event type from the sandbox environment since it's not valid anymore.
