### ISSUE TITLE
Consider using application/json-seq as a Content-Type for streaming

### ISSUE THREAD

**Issue by whiskeysierra** [zalando/nakadi#279]
Right now the `/event-types/{type}/events` uses

``` http
Content-Type: text/plain;charset=UTF-8
```

I think [`application/json-seq`](https://tools.ietf.org/html/rfc7464) would be a better fit.

**Comment by AlexanderYastrebov** [comment]
This was changed to `application/x-json-stream` recently
See https://github.com/zalando/nakadi/commit/9b8eea8973eb8e2dea347ba43d2b9084bcc8ec1f

**Comment by whiskeysierra** [comment]
But application/json-seq is not a custom extension (`x-`).

**Comment by AlexanderYastrebov** [comment]
Your proposal requires ASCII Record Separator to be inserted which will break some clients for sure

**Comment by dehora** [comment]
> application/json-seq is not a custom extension 

The lazy counter argument to `x-` is usually `application/x-www-form-urlencoded` ;) But I think there's value in Nakadi supporting an RFC - streaming JSON is kind of all over the place standards-wise and 9b8eea8 is really about making good on an existing commitment in the API definition. My personal bias is really about what's good/useful to clients, but a quick overview of the `application/json-seq` type's technical approach to framing would be very useful to assess it.

**Comment by rcillo** [comment]
In order not to introduce backward incompatible changes we will remain using `application/x-json-stream`

**Comment by whiskeysierra** [comment]
What about Content Negotiation and supporting both?

**Comment by lmontrieux** [comment]
@rcillo @dehora This has been opened over a year ago, and inactive for almost as long. Should I close this?

**Comment by rcillo** [comment]
@lmontrieux I think we should close it. Even though it is a low hanging fruit, at the same time I think that content negotiation is something that makes maintaining the system more expensive, because you need to be sure that 2 modes of writing data are correctly implemented. Configurations lead to an exponential growth in complexity so I have my doubts about the pros and cons here. I think that if we are adding a feature that delivers the same thing as an existing one, we should plan to deprecated the existing one, in order not to grow the complexity of the product and the code.

**Comment by lmontrieux** [comment]
@rcillo @dehora I'm closing this as it has been inactive for a long time, and a solution would entail a lot of additional complexity. Feel free to re-open if you think it is still relevant.
