### ISSUE TITLE
Problem response for no longer available offsets should contain information about available offsets

### ISSUE THREAD

**Issue by jhorstmann** [zalando/nakadi#344]
When managing offsets locally and when this consumer is stopped for a longer time it can happen that events expire. Trying to stream from the last processed offset then leads to the following error response:

    $ curl -H "Authorization: Bearer $TOKEN" -H 'X-Nakadi-Cursors:[{"partition": "0", "offset":"47"}]' https://example.com/event-types/order-placed/events
    {
      "type": "http://httpstatus.es/412",
      "title": "Precondition Failed",
      "status": 412,
      "detail": "offset 47 for partition 0 is unavailable"
    }

It would be nice if this response contains the partition and oldest offset that it would be possible to stream as separate properties, so that clients can handle this automatically and do not have parse error messages query partitions before connecting.

**Comment by zd0** [comment]
I want to propose different approach: be more tolerable for cursors with offsets that are already expired. It can be done by introducing new parameter, that will interpret the cursors in non strict way (in case if you don't want to brake the clients that rely on current behaviour).

The problem is that reading offsets is not atomic (happens in multiple service requests): even if the client re-inits offsets according to offsets you provide in the error (as proposed here) or by calling `GET /event-types/${event}/partitions`, you still can imagine that Nakadi removes some other events instances due to expiration.

With current state of affairs, clients have to retry multiple times to connect for streaming (request available offsets + try to connect). This complicates the clients with not much meaning.

**Comment by jhorstmann** [comment]
> be more tolerable for cursors with offsets that are already expired

That sounds like an even better solution for my use case

**Comment by tmuehl** [comment]
@zd0 You don't have to reconnect multiple time if you use the cursor `BEGIN`. You should reconnect with the `oldest_available_offset` anyway because the Nakadi-Cursors are exclusive and you will loose this one event.

The intention behind it all, is that a client doesn't loose events without recognizing.

**Comment by zd0** [comment]
@tmuehl, the point of my complain is that clients have to be smart, to fight the inconvinience of the service.
In this situation (when some offsets are expired):
 * client has to connect to stream data -> gets 412 error from the service.
 * client decides to retry: makes `GET /event-types/{topic}/events` to retrieve valid offsets
 * adjusts request offsets (by setting "BEGIN" for outdated partitions)
 * connect again to stream data (NB: the second attempt also can fail, because the system still can expire some other partitions of the topic).

The service already has offsets in the events, and the system guarantees(?) that offsets are in non-descending order. So, if you really want to inform the client that some events are expired, then the client can figure this out by comparing:
 * offset in the batch event;
 * how many events in the batch;
 * what was the last local offset at the client side.

**P.S.:** are there any guarantees about offsets? can clients miss some data due to expiration process in the background?
For example, you can imagine a slow client that processes events. While it processes some event (offset = i), the system expires some events (with offsets i, i+1, .., i+k). Will the slow client still receive those expired events (in the same connection stream)?

**Comment by jhorstmann** [comment]
@zd0 Except for retrying multiple times, that's the strategy I implemented in the [fahrschein CursorManager](https://github.com/zalando-incubator/fahrschein/blob/0.4.2/src/main/java/org/zalando/fahrschein/CursorManager.java#L58).

> the system guarantees(?) that offsets are in non-descending order.

From what I heard the numeric offsets should be considered an implementation detail and we should not rely on them being numeric or comparable.

**Comment by rcillo** [comment]
Clients can query Nakadi for available offset using `GET /event-types/{topic}/partitions`.

Defining if a given offset has already expired is possible by comparing with the result from the endpoint above.

Opening streams using unavailable (expired) offsets is not supported. Please, consider using `BEGIN` instead.

Yes, slow clients can miss data. We are about to release a feature to improve that https://github.com/zalando/nakadi/pull/351

Offsets are officially supposed to be opaque entities, but I'll tell you a secret, they are monotonically increasing 😶

**Comment by zd0** [comment]
@jhorstmann 
> we should not rely on them being numeric or comparable.
Still you are comparing offsets in your code. And personally, I don't have any idea how to avoid comparing at all: there is still some manipulations involved to interact with Nakadi properly;
and one of them is mentioned here.

@rcillo you are repeating what I have already described, how it has to be done now. But I request to simplify the system and be more tolerable for clients. In particular, remove this restriction:
> Opening streams using unavailable (expired) offsets is not supported.
You can have additional parameter for clients, which will tell the service that client acknowledges, that the system won't complain about expired offset and will stream data from oldest available offset.

#351 is partial solution, and rather a new "tuning" option for topics. Imagine some consumer service was offline for 1 century. If events are lost, then so to be, but it shouldn't be a barrier to consume what is there now.

>Offsets are officially supposed to be opaque entities
Please, try to implement adequate consuming client without relying on ordering assumption (or at least give an implementation recommendation in plain text). This can be used as guidance for client implementers. (I know about HL api, which hides cursors handling).

> can clients miss some data due to expiration process in the background?
>For example, you can imagine a slow client that processes events. While it processes some event >(offset = i), the system expires some events (with offsets i, i+1, .., i+k). Will the slow client still >receive those expired events (in the same connection stream)?
So, is such situation possible and how clients will be notified in this case about expired events? Or the system will just close connection when there are "holes" in topic stream?

**Comment by tmuehl** [comment]
@zd0 The scenario in general sounds to me more like a problem with too short retention times.
The expires-while-consuming example is not very probable. It would either mean that your application is 3 or 7 days delayed with consumption or it took your application 3 or 7 days to consume one event. Hence, either the consumer is not able keep up with the stream or the retention time is configured too short.

> @rcillo you are repeating what I have already described, how it has to be done now.

I think, @rcillo suggested to use the `/partition` endpoint to get up-to-date offsets instead of `/events`.

However, I agree, that it would be very helpful for clients if the Nakadi response includes the outdated partitions in case of a `412`.

**Comment by zd0** [comment]
There was my typo, in my second comment about the exact api endpoint. Sorry if it was not clear from intent.

Is it possible that a topic stream contains array of events with posted date very close to each other. The first event we start to read is almost expired (but still has a few seconds to live). The same is true for next 1000 events (the expiration time difference of those events is very low, they were put into topic by very fast producer, for example 4 seconds between the first event and 1000th).

The client was sleeping for some time (due to some reason). And now starts to consume the stream, and receives the first event from the service. It slowly processes the first event (for example, it takes 5 seconds).

At the same time, at Nakadi side, all those 1000 events has expired.

The client has processed the first event, and now continues to process next. What will client get?

Is my example not realistic?

**Comment by rcillo** [comment]
Since "/partitions" already provides this information we are not including this in a client error response. Consider using `begin` in this case or if managing offsets is too much of a burden, take a look at subscriptions API https://github.com/zalando/nakadi/pull/353.

As for a consumer that is not able to keep up with producers speed, it will eventually fall behind of the retention window and start loosing events. There's not much Nakadi can do about it besides replying with 412 as it already does when such a client tries to open a stream from an expired offset. It's up to the consumer to monitor this and keep up with producers rate.
