### ISSUE TITLE
Deprecated batch_limit parameter from streaming endpoints (low and high level)

### ISSUE THREAD

**Issue by rcillo** [zalando/nakadi#404]
In order to provide an easier to use, easier to test, less error prone, easier to operate, more stable and safer application, I would like to propose the deprecation of the batch_limit parameter.

This option is potentially dangerous since it allows for clients to allocate memory on the server at will. If a client asks for a very large batch_limit, it might allocate a lot of memory on the server, since it would batch a very large number of events before delivering.

Currently, it's really easy to break Nakadi. Just stream from an event type with lots of events, set very high batch_limit and batch_flush_timeout. It will consume all of servers memory and make it inoperable.

The consequence of removing this option would mean that clients would have to worry with one less parameter (currently there are 5) that have interdependencies, leading to a very high number of configurations, making it hard to understand the behaviour of the stream.

Instead, we could decide dynamically on the size of the batch and make no guarantees on how many events will be batched, since it's more of a server limitation (memory usage and bandwidth efficiency) than a client's matter.

@dehora @v-stepanov @v1ctor @adyach

**Comment by v-stepanov** [comment]
I actually think this is the most useful parameter we have. All other parameters are much less useful (especially `keep_alive_limit` - I hate it and I think nobody uses it)
If we have memory considerations we should just limit the max value for `batch_limit` parameter.

**Comment by rcillo** [comment]
You are right. We might go into persons preference discussion. We should collect statistics of how many users are using this, which values and why. Then we could have a more clear understanding of the real value of this parameter.

**Comment by adyach** [comment]
I think you can say that way about any parameter :) We could start hila without all of these parameters adding them when the users will really need them.

**Comment by dehora** [comment]
> Currently, it's really easy to break Nakadi. Just stream from an event type with lots of events, set very high batch_limit and batch_flush_timeout. It will consume all of servers memory and make it inoperable.

If this is true, I'm :+1: to dropping. The server has to have the option to control its own resources; imo that trumps convenience features, especially for a multi-tenant deployment. 

> We could start hila without all of these parameters adding them when the users will really need them.

We touched on this in https://github.com/zalando/nakadi/pull/353#issuecomment-238514240 in terms of how connection parameters might interact with each in surprising (and bad) ways. I'd just drop them instead of waiting for outages or flashes of insight to learn how they work.

>If we have memory considerations we should just limit the max value for batch_limit parameter.

I'm wondering if it can happen as well with a lot of held connections with smaller batches but busier streams. If it's a dynamic problem, one way it can be managed on a held/push connection model is to allow the server to autosize its batches instead of the statically allocating resources; but that's not an option if the client can define the allocation. 

> We should collect statistics of how many users are using this, which values and why.

We can do that, but the observation I'd make is that if it's there people will use it :)

**Comment by lmontrieux** [comment]
@rcillo @v-stepanov @dehora @adyach what are we doing with this? It's been inactive for a while.

**Comment by krnkl** [comment]
> > We should collect statistics of how many users are using this, which values and why.

> We can do that, but the observation I'd make is that if it's there people will use it :)
@lmontrieux 
Our team is relying on this parameter. Its safe for us to process only one event in the batch and commit it if processing was successful. Further, parallel processing can be achieved by starting as many clients to read this subscription as we have partitions configured for the event-type. So parallelism lets say restricted.

On the other hand if we would read batch with multiple events and commit only when all events in the batch are successfully processed  - we will have more risks that processing will take more time, stream will be restarted due to network error or smth else - and whole batch won't be committed, which will lead to the situations when event  will be processed multiple times.

**Comment by whiskeysierra** [comment]
I agree with @v-stepanov. The batch limit is crucial for clients. Nakadi imposes that clients commit at least every 60 seconds and it's impossible to commit a batch partially. That means the batch limit is the only tool clients have to ensure that it's able to process all events of a batch within 60 seconds.

**Comment by rcillo** [comment]
Actually the problem that I originally raised in this issue happened on live and caused an incident. We already solved it by putting a hard limit on 50 MB batch size. So, next time, let's try to be more pragmatic and find solutions that avoid incidents, like putting the 50 MB limit.
