### ISSUE TITLE
Make commit timeout configurable

### ISSUE THREAD

**Issue by tmuehl** [zalando/nakadi#594]
If a subscription API consumer doesn't commit a batch within 60s, Nakadi considers the connection as broken.

*As* a consumer of the subscription API
*I want to* be able to configure this setting to another value (e.g. 5min)
*Such that* I don't break if I need longer and can e.g. implement back pressure.

##### Explanation for the back pressure:
We consume events and write them into a datastore. If our datastore becomes slow, we might come into a situation where we cannot write events in the same pace to the datastore in which we consume them from Nakadi. Hence, we throttle Nakadi consumption by delaying the commit.
Is there a better way to do that?

**Comment by rcillo** [comment]
@tmuehl making commit timeout configurable could have other undesirable consequences. For example, let's suppose the connection is broken, but Nakadi is not notified about it (it happens all the time). Than, client will try to reconnect but the slot is already taken by the previous connection. If the timeout has been set to 5 minutes, it might be that the client will have to wait for 5 minutes to reconnect.

One alternative way I could think about solving this problem is for Nakadi to accept already committed offsets as a kind of "client keep-alive". 

So clients could have 2 threads, 1 consumer and 1 committer.

The consumer, reads a batch, process it and tell the committer once it's done.
The committer can immediately commit the cursor to Nakadi or even throttle it, if the commit rate is to big.
If the committer has nothing new to commit, it commits the latest committed cursor just to keep the connection open.

What do you think about this approach?

**Comment by rcillo** [comment]
I would say that ideally we should reduce commit timeout and require clients to send keep alives at every 30 seconds or less, so that broken connections are quickly detected and the client can reconnect as fast as possible.

**Comment by tmuehl** [comment]
@rcillo Eventually, I am looking for a good solution to implement back pressure to Nakadi consumption. Such, I am happy about any scalable solution. Your suggestion about "keep-alive commit" sound promising. Having two threads, how would you avoid that the consumer dies while the committer is still running?

Regarding a flexible commit timeout: You still provide a feasible default. If a clients explicitly configures this setting to a different value, it's their responsibility. And the client knows best if it's in their scenario ok to wait 5 minutes for the free slot or not. For some applications it might make sense - like for ours. 😊

**Comment by rcillo** [comment]
Coordinating thread unexpected termination in Java could be achieved in different ways depending on which interfaces are used. If the consumer is a Runnable and it throws a runtime exception, it could be handled by an UncaughtExceptionHandler and the committer could then be interrupted nicely (maybe even waiting for the last commit to finish).

Or if a Future is used it would be another approach. I'm quite confident that there is always a way to do it in Java.

I recently spent some time reading Kafka Java client. It uses concurrency to implement several tasks like fetching, keep alives, commits, metadata updates, pipeline fetch (fetch ahead), and so on.

I think that the sequential approach 1. read, 2. process, 3. commit, 4. repeat doesn't scale.

I had never implemented a Nakadi client, so my experience is zero, but I would try to do something similar to Kafka client because it has some cool ideas.

Meanwhile, my suggestion is to reduce batch sizes so that it's possible to process one batch every 60 seconds.

**Comment by tmuehl** [comment]
> Coordinating thread unexpected termination in Java could be achieved in different ways depending on which interfaces are used. If the consumer is a Runnable and it throws a runtime exception, it could be handled by an UncaughtExceptionHandler and the committer could then be interrupted nicely (maybe even waiting for the last commit to finish).

It sound like effort and complexity every client needs to take. If consumers don't close the connection correctly on their side in case of an exception, it's rather uncertain they implement this correctly.

> I think that the sequential approach 1. read, 2. process, 3. commit, 4. repeat doesn't scale.

Can you explain why you think so?

> Meanwhile, my suggestion is to reduce batch sizes so that it's possible to process one batch every 60 seconds.

That's what we did and it's a nice work around. The downside is that the consumer is artificially throttled. Usually we process a batch in 1-3 seconds. But ca. 3 times a day it happens that it takes > 60s because of back pressure, a third party call takes longer (maybe because we need to retry there) and so on.

Does Nakadi itself suffer from higher commit timeouts if explicitly set by a client?

**Comment by bocytko** [comment]
I second @tmuehl's request. Until the keep-alive is provided, it will be great to have a possibility to set the timeout to a desired value and avoid dynamic batch size calculation on client side.

**Comment by rcillo** [comment]
We could off course make it variable. From Nakadi's infrastructure point of view the impact would be minimum. Since the number of open connections is limited by the number of partitions, I do not fear any overhead.

The problem I see is that once we introduce it, we would no longer be able to remove it, since it would be an incompatible change. So if someone decides that for their application it makes sense to have 24 hour commit timeout (as requested in the past), but the connection is actually dead or the client has some problem, it could take Nakadi 24 hours to detect it and the client would be unable to reconnect since no free slots would be available. Meanwhile Nakadi instance holding this connections could be terminated, for example, with a very high probability. I think clients should not rely on connections to be stable on such a large timescale.

Regarding optimal client implementation, I'll move the discussion to another forum, since it slightly deviates from the commit timeout discussion.

I have two questions before delivering this feature:

Why taking smaller batches is a problem?

What should be considered a reasonable maximum commit timeout?

**Comment by rcillo** [comment]
@tmuehl @bocytko I implemented it with a range limit from actual 60 to 300 seconds https://github.com/zalando/nakadi/pull/604

Lets discuss with other maintainers if someone has something against it.

@v-stepanov @antban @adyach @lmontrieux @SergKam @dehora @valgog

**Comment by dehora** [comment]
> I implemented it with a range limit from actual 60 to 300 seconds
> Lets discuss with other maintainers if someone has something against it.

Ok, let's see how that works. I'm kind of concerned with this change. 

The current protocol designs out back pressure options such that the best overall systems option is for clients to disconnect and reconnect emulating a pagination model (like for example, Kinesis). Holding a connection open for longer to allow a client time isn't back pressure, it's increasing the likelihood of cascading failures (it's basically the opposite of a fast fail circuit breaking strategy). It also means the service is giving over resources and connections to slow consumers which couples consumer/producer throughput and stops it allocating those resources that can't make progress (potentially increasing service costs as it requires more server nodes). There are further complications like the fact that clients can't commit when session ids change due to regular disconnects, and part of me thinks a better direction is to allow more relaxed checkpointing options and enable a model where reconnecting is a natural thing to .

So for now, like I said, let's see how it goes. Longer term, this direction isn't going to scale for our needs. We need to figure out batch consuming that uses http optimally, and/or, get to a bidirectional approach for connected clients.

/ @v-stepanov @antban @adyach @lmontrieux @SergKam @dehora @valgog

**Comment by adyach** [comment]
@dehora 
> get to a bidirectional approach for connected clients

+1

**Comment by phibrex** [comment]
ARUHA-986 was added to our backlog.

**Comment by lmontrieux** [comment]
Fixed in #969 . It is now possible to set a commit timeout between 1 and default_commit_timeout
