### ISSUE TITLE
Exactly-once

### ISSUE THREAD

**Issue by cbornet** [zalando/nakadi#976]
Is Nakadi capable of exactly-once ? 
Kafka can dedup produced messages if `enable.idempotence=true` is set.
But putting Nakadi in between, if a Nakadi node crashes while producing, the producer can't know if the message was written to Kafka. So it seems Nakadi is not able to do exactly-once.
Is my analysis correct ?

**Comment by rcillo** [comment]
You are right. Nakadi guarantees only at-least-once delivery semantics. It's important to mention that Nakadi does not automatically retries and that the single source of duplicates are client retries. Clients might retry because they are not willing to wait forever for a response (not only because Nakadi crashed).

Kafka achieves "exactly once" semantics through a combination of broker feature support and client code. It's a combination of idempotence based on message sequencing, transactions and a full client library support for "streams API". Nakadi, so far, only focuses on the service layer (equivalent to Kafka's broker, if such analogy is even possible).

If you are interested into bringing "exactly once" to Nakadi, I imagine it would require detailing the roles of Nakadi the service and the clients in order to achieve that. For example, Nakadi the service definitely should allow producers to turn on "idempotence" for topics. But that alone would not be enough. A lot of the work confluent did was to make sure the solution works as a whole, including the client.

**Comment by rcillo** [comment]
If you don't mind, I'll close the issue since the original question has been answered.

**Comment by cbornet** [comment]
I guess it would require a shared space to store sequenceIDs (ZooKeeper?) and an internal dedup mecanism with maybe the possibility for the producer to pass its own unique sequenceID (like is done in Pulsar). I agree that it's probably out of scope of Nakadi. Thanks for your answer.

**Comment by rcillo** [comment]
Yes, I agree with you. It would probably be a way to achieve that. I don't say that it's not in our interest to support that, but that would require extending the idea of what is Nakadi to beyond a simple API. The client would play a very important role as well.
